export const solar = [
  {
    power: 240,
    power_unit: "W",
    type: "monocristalino",
    max_power_current: 5.9,
    shortcircuit_current: 6.3,
    current_unit: "A",
    efficiency: 19.8,
    efficiency_unit: "%",
    operating_temperature: 45,
    temperature_unit: " \u00b0 C",
    max_voltage: 40.7,
    shortcircuit_voltage: 48.4,
    working_voltage: 12,
    voltage_unit: "V",
    junction_box: "IP 68",
    product_warranty: 15,
    linear_output_power_warranty: 30,
    warranty_unit: "a\u00f1os",
    long: 1568,
    width: 770,
    high: 30,
    dimension_unit: "mm",
    weight: 15.0,
    weight_unit: "kg",
    price: 264895,
    url: "https://autosolar.co/paneles-solares-12v/panel-solar-monocristalino-240w-tensite",
  },
  {
    power: 380,
    power_unit: "W",
    type: "monocristalino",
    max_power_current: 9.5,
    shortcircuit_current: 10.05,
    current_unit: "A",
    efficiency: 19.6,
    efficiency_unit: "%",
    operating_temperature: 45,
    temperature_unit: " \u00b0 C",
    max_voltage: 40.03,
    shortcircuit_voltage: 48.71,
    working_voltage: 24,
    voltage_unit: "V",
    junction_box: "IP 67 ",
    product_warranty: 12,
    linear_output_power_warranty: 25,
    warranty_unit: "a\u00f1os",
    long: 1960,
    width: 991,
    high: 40,
    dimension_unit: "mm",
    weight: 22.0,
    weight_unit: "kg",
    price: 615938,
    url: "https://autosolar.co/paneles-solares-24v/panel-solar-340w-24v-monocristalino-perc-ja-solar",
  },
  {
    power: 450,
    power_unit: "W",
    type: "monocristalino",
    max_power_current: 10.87,
    shortcircuit_current: 11.44,
    current_unit: "A",
    efficiency: 20.6,
    efficiency_unit: "%",
    operating_temperature: 45,
    temperature_unit: " \u00b0 C",
    max_voltage: 41.4,
    shortcircuit_voltage: 50.0,
    working_voltage: 24,
    voltage_unit: "V",
    junction_box: "IP 68",
    product_warranty: 12,
    linear_output_power_warranty: 25,
    warranty_unit: "a\u00f1os",
    long: 2102,
    width: 1040,
    high: 35,
    dimension_unit: "mm",
    weight: 24.5,
    weight_unit: "kg",
    price: 889963,
    url: "https://autosolar.co/paneles-solares-24v/panel-solar-450w-24v-monocristalino-perc-ecogreen",
  },
  {
    power: 455,
    power_unit: "W",
    type: "monocristalino",
    max_power_current: 10.92,
    shortcircuit_current: 11.41,
    current_unit: "A",
    efficiency: 20.4,
    efficiency_unit: "%",
    operating_temperature: 45,
    temperature_unit: " \u00b0 C",
    max_voltage: 41.82,
    shortcircuit_voltage: 49.85,
    working_voltage: 24,
    voltage_unit: "V",
    junction_box: "IP 68",
    product_warranty: 12,
    linear_output_power_warranty: 25,
    warranty_unit: "a\u00f1os",
    long: 2120,
    width: 1052,
    high: 40,
    dimension_unit: "mm",
    weight: 25.0,
    weight_unit: "kg",
    price: 594693,
    url: "https://autosolar.co/paneles-solares-24v/panel-solar-ja-solar-455w-24v-monocristalino-perc",
  },
  {
    power: 550,
    power_unit: "W",
    type: "monocristalino",
    max_power_current: 13.11,
    shortcircuit_current: 13.93,
    current_unit: "A",
    efficiency: 21.3,
    efficiency_unit: "%",
    operating_temperature: 45,
    temperature_unit: " \u00b0 C",
    max_voltage: 41.8,
    shortcircuit_voltage: 49.75,
    working_voltage: 24,
    voltage_unit: "V",
    junction_box: "IP 68",
    product_warranty: 12,
    linear_output_power_warranty: 25,
    warranty_unit: "a\u00f1os",
    long: 2278,
    width: 1134,
    high: 33,
    dimension_unit: "mm",
    weight: 27.8,
    weight_unit: "kg",
    price: 1152002,
    url: "https://autosolar.co/paneles-solares-24v/panel-solar-550w-24v-monocristalino-perc-ecogreen",
  },
  {
    power: 610,
    power_unit: "W",
    type: "monocristalino bifacial",
    max_power_current: 15.34,
    shortcircuit_current: 16.05,
    current_unit: "A",
    efficiency: 22.6,
    efficiency_unit: "%",
    operating_temperature: 45,
    temperature_unit: " \u00b0 C",
    max_voltage: 45.0,
    shortcircuit_voltage: 48.1,
    working_voltage: 24,
    voltage_unit: "V",
    junction_box: "IP 68",
    product_warranty: 15,
    linear_output_power_warranty: 30,
    warranty_unit: "a\u00f1os",
    long: 2384,
    width: 1134,
    high: 30,
    dimension_unit: "mm",
    weight: 28.5,
    weight_unit: "kg",
    price: 605363,
    url: "https://autosolar.co/paneles-solares-24v/panel-solar-bifacial-610w-n-type-tensite",
  },
  {
    power: 710,
    power_unit: "W",
    type: "monocristalino",
    max_power_current: 17.45,
    shortcircuit_current: 18.45,
    current_unit: "A",
    efficiency: 22.86,
    efficiency_unit: "%",
    operating_temperature: 45,
    temperature_unit: " \u00b0 C",
    max_voltage: 40.69,
    shortcircuit_voltage: 48.94,
    working_voltage: 24,
    voltage_unit: "V",
    junction_box: "IP 68",
    product_warranty: 15,
    linear_output_power_warranty: 30,
    warranty_unit: "a\u00f1os",
    long: 2384,
    width: 1303,
    high: 35,
    dimension_unit: "mm",
    weight: 37.7,
    weight_unit: "kg",
    price: 704603,
    url: "https://autosolar.co/paneles-solares-24v/panel-solar-bifacial-710w-n-type-tensite",
  },
];

export const investor = [
  {
    input_voltage: 12,
    output_voltage: 110,
    voltage_unit: "V",
    continuous_power: 600,
    power_unit: "W",
    efficiency: 90,
    efficiency_unit: "%",
    long: 367,
    width: 150,
    high: 76,
    dimension_unit: "mm",
    weight: 2.75,
    weight_unit: "kg",
    price: 408534,
    url: "https://autosolar.co/inversores-de-corriente/inversor-de-corriente-onda-pura-600w-12v-belttt",
  },
  {
    input_voltage: 12,
    output_voltage: 110,
    voltage_unit: "V",
    continuous_power: 1000,
    power_unit: "W",
    efficiency: 90,
    efficiency_unit: "%",
    long: 367,
    width: 150,
    high: 76,
    dimension_unit: "mm",
    weight: 2.75,
    weight_unit: "kg",
    price: 725331,
    url: "https://autosolar.co/inversores-de-corriente/inversor-de-corriente-onda-pura-1000w-12v-belttt",
  },
  {
    input_voltage: 24,
    output_voltage: 110,
    voltage_unit: "V",
    continuous_power: 600,
    power_unit: "W",
    efficiency: 90,
    efficiency_unit: "%",
    long: 367,
    width: 150,
    high: 76,
    dimension_unit: "mm",
    weight: 2.75,
    weight_unit: "kg",
    price: 579481,
    url: "https://autosolar.co/inversores-solares-24v/phoenix-inverter-24500-120v-vedirect-nema-5-15r",
  },
  {
    input_voltage: 24,
    output_voltage: 110,
    voltage_unit: "V",
    continuous_power: 1000,
    power_unit: "W",
    efficiency: 90,
    efficiency_unit: "%",
    long: 367,
    width: 150,
    high: 76,
    dimension_unit: "mm",
    weight: 2.75,
    weight_unit: "kg",
    price: 1305579,
    url: "https://autosolar.co/inversores-solares-24v/phoenix-inverter-241200-120v-vedirect-nema-5-15r",
  },
];

export const drivers = [
  {
    model: "MPPT  100/20",
    system_voltage_1: 12,
    system_voltage_2: 24,
    shortcircuit_voltage: 100,
    voltage_unit: "V",
    max_charging_current: 20,
    current_unit: "A",
    power_by_voltage_1: 290,
    power_by_voltage_2: 580,
    power_unit: "W",
    efficiency: 98,
    efficiency_unit: "%",
    price: 816667,
    url: "https://autosolar.co/controladores-de-carga-mppt/controlador-carga-bluesolar-mppt-100v-20a-48v-victron-energy",
  },
  {
    model: "MPPT 40  12/24 V   LCD",
    system_voltage_1: 12,
    system_voltage_2: 24,
    shortcircuit_voltage: 100,
    voltage_unit: "V",
    max_charging_current: 20,
    current_unit: "A",
    power_by_voltage_1: 260,
    power_by_voltage_2: 520,
    power_unit: "W",
    efficiency: 98,
    efficiency_unit: "%",
    price: 565718,
    url: "https://autosolar.co/controladores-de-carga-mppt/controlador-carga-mppt-30a-ml4830n15-12243648v-lcd-srne",
  },
  {
    model: "MPPT  SC4880  ",
    system_voltage_1: 12,
    system_voltage_2: 24,
    shortcircuit_voltage: 150,
    voltage_unit: "V",
    max_charging_current: 80,
    current_unit: "A",
    power_by_voltage_1: 1250,
    power_by_voltage_2: 2500,
    power_unit: "W",
    efficiency: 99,
    efficiency_unit: "%",
    price: 1340685,
    url: "https://autosolar.co/controladores-de-carga-mppt/controlador-growatt-mppt-sc4880-80a",
  },
  {
    model: "MPPT  Blue Solar   48 V",
    system_voltage_1: 12,
    system_voltage_2: 24,
    shortcircuit_voltage: 100,
    voltage_unit: "V",
    max_charging_current: 20,
    current_unit: "A",
    power_by_voltage_1: 290,
    power_by_voltage_2: 580,
    power_unit: "W",
    efficiency: 98,
    efficiency_unit: "%",
    price: 485294,
    url: "https://autosolar.co/controladores-de-carga-pwm/controlador-carga-bluesolar-pwm-lcdusb-48v-30a-victron-energy",
  },
  {
    model: "MPPT  30 A  MC2430N10",
    system_voltage_1: 12,
    system_voltage_2: 24,
    shortcircuit_voltage: 100,
    voltage_unit: "V",
    max_charging_current: 30,
    current_unit: "A",
    power_by_voltage_1: 400,
    power_by_voltage_2: 800,
    power_unit: "W",
    efficiency: 95,
    efficiency_unit: "%",
    price: 548050,
    url: "https://autosolar.co/controladores-de-carga-mppt/controlador-carga-mppt-30a-ml2430-1224v-lcd-srne",
  },
  {
    model: "Smart Solar MPPT  100 / 15",
    system_voltage_1: 12,
    system_voltage_2: 24,
    shortcircuit_voltage: 100,
    voltage_unit: "V",
    max_charging_current: 15,
    current_unit: "A",
    power_by_voltage_1: 220,
    power_by_voltage_2: 440,
    power_unit: "W",
    efficiency: 98,
    efficiency_unit: "%",
    price: 624000,
    url: "https://autosolar.co/controladores-de-carga-mppt/controlador-carga-smartsolar-mppt-10015-retail-victron-energy",
  },
  {
    model: "Blue Solar MPPT  75/ 10",
    system_voltage_1: 12,
    system_voltage_2: 24,
    shortcircuit_voltage: 75,
    voltage_unit: "V",
    max_charging_current: 10,
    current_unit: "A",
    power_by_voltage_1: 145,
    power_by_voltage_2: 290,
    power_unit: "W",
    efficiency: 98,
    efficiency_unit: "%",
    price: 719697,
    url: "https://autosolar.co/controladores-de-carga-mppt/controlador-carga-bluesolar-mppt-7510-retail-victron-energy",
  },
  {
    model: "Smart Solar MPPT  75 / 15",
    system_voltage_1: 12,
    system_voltage_2: 24,
    shortcircuit_voltage: 75,
    voltage_unit: "V",
    max_charging_current: 15,
    current_unit: "A",
    power_by_voltage_1: 220,
    power_by_voltage_2: 440,
    power_unit: "W",
    efficiency: 98,
    efficiency_unit: "%",
    price: 847855,
    url: "https://autosolar.co/controladores-de-carga-mppt/controlador-carga-smartsolar-mppt-7515-retail-victron-energy",
  },
  {
    model: "MPPT  30 A  ML4830N15",
    system_voltage_1: 12,
    system_voltage_2: 24,
    shortcircuit_voltage: 145,
    voltage_unit: "V",
    max_charging_current: 30,
    current_unit: "A",
    power_by_voltage_1: 400,
    power_by_voltage_2: 800,
    power_unit: "W",
    efficiency: 99,
    efficiency_unit: "%",
    price: 565718,
    url: "https://autosolar.co/controladores-de-carga-mppt/controlador-carga-mppt-40a-ml2440-1224v-lcd-srne",
  },
];

export const batteries = [
  {
    type: "GEL",
    nominal_voltage: 12,
    voltage_unit: "V",
    nominal_capacity: 300,
    capacity_unit: "Ah",
    cells_per_battery: 6,
    max_discharge_current: 2500,
    max_charging_current: 75,
    current_unit: "A",
    long: 520,
    width: 268,
    high: 220,
    dimension_unit: "mm",
    weight: 67.0,
    weight_unit: "kg",
    price: 1620237,
    url: "https://autosolar.co/baterias-gel-12v/bateria-gel-12v-300ah-tensite",
  },
  {
    type: "GEL",
    nominal_voltage: 12,
    voltage_unit: "V",
    nominal_capacity: 250,
    capacity_unit: "Ah",
    cells_per_battery: 6,
    max_discharge_current: 2000,
    max_charging_current: 60,
    current_unit: "A",
    long: 522,
    width: 240,
    high: 218,
    dimension_unit: "mm",
    weight: 57.0,
    weight_unit: "kg",
    price: 1379799,
    url: "https://autosolar.co/baterias-gel-12v/bateria-gel-12v-250ah-tensite",
  },
  {
    type: "GEL",
    nominal_voltage: 12,
    voltage_unit: "V",
    nominal_capacity: 150,
    capacity_unit: "Ah",
    cells_per_battery: 6,
    max_discharge_current: 1200,
    max_charging_current: 36,
    current_unit: "A",
    long: 407,
    width: 174,
    high: 215,
    dimension_unit: "mm",
    weight: 33.6,
    weight_unit: "kg",
    price: 830278,
    url: "https://autosolar.co/baterias-gel-12v/bateria-gel-12v-150ah-tensite",
  },
  {
    type: "GEL",
    nominal_voltage: 12,
    voltage_unit: "V",
    nominal_capacity: 100,
    capacity_unit: "Ah",
    cells_per_battery: 6,
    max_discharge_current: 900,
    max_charging_current: 18,
    current_unit: "A",
    long: 319,
    width: 172,
    high: 218,
    dimension_unit: "mm",
    weight: 26.2,
    weight_unit: "kg",
    price: 630849,
    url: "https://autosolar.co/baterias-gel-12v/bateria-gel-12v-100ah-tensite",
  },
  {
    type: "AGM",
    nominal_voltage: 12,
    voltage_unit: "V",
    nominal_capacity: 255,
    capacity_unit: "Ah",
    cells_per_battery: 6,
    max_discharge_current: 1800,
    max_charging_current: 75,
    current_unit: "A",
    long: 521,
    width: 269,
    high: 220,
    dimension_unit: "mm",
    weight: 78.0,
    weight_unit: "kg",
    price: 1791600,
    url: "https://autosolar.co/baterias-agm-12v/bateria-agm-255ah-12v-mtek-vrl",
  },
  {
    type: "AGM ",
    nominal_voltage: 12,
    voltage_unit: "V",
    nominal_capacity: 18,
    capacity_unit: "Ah",
    cells_per_battery: 6,
    max_discharge_current: 270,
    max_charging_current: 70,
    current_unit: "A",
    long: 181,
    width: 77,
    high: 167,
    dimension_unit: "mm",
    weight: 5.3,
    weight_unit: "kg",
    price: 155055,
    url: "https://autosolar.co/baterias-agm-12v/bateria-agm-12v-18ah-tensite",
  },
  {
    type: "GEL",
    nominal_voltage: 12,
    voltage_unit: "V",
    nominal_capacity: 90,
    capacity_unit: "Ah",
    cells_per_battery: 6,
    max_discharge_current: 800,
    max_charging_current: 48,
    current_unit: "A",
    long: 329,
    width: 172,
    high: 218,
    dimension_unit: "mm",
    weight: 26.0,
    weight_unit: "kg",
    price: 793722,
    url: "https://autosolar.co/baterias-gel-12v/bateria-gel-12v-90ah-tensite",
  },
];
